/**
 * NETOPIA Payment API v2.x - Conform documentației oficiale
 * https://doc.netopia-payments.com/docs/payment-api/v2.x/introduction
 *
 * Această implementare folosește API KEY în loc de POS signature
 * și JSON requests în loc de form POST
 */

// Configurație pentru NETOPIA API v2.x
const NETOPIA_V2_CONFIG = {
  sandbox: {
    baseUrl: "https://sandbox.netopia-payments.com",
    apiKey:
      process.env.NETOPIA_SANDBOX_API_KEY || process.env.NETOPIA_LIVE_API_KEY, // Fallback la live key pentru testare
  },
  live: {
    baseUrl: "https://secure.netopia-payments.com",
    apiKey: process.env.NETOPIA_LIVE_API_KEY, // API KEY pentru producție
  },
};

/**
 * Creează payload-ul pentru NETOPIA API v2.x
 * Conform documentației: https://netopia-system.stoplight.io/docs/payments-api
 */
function createNetopiaV2Payload(paymentData, config) {
  const baseUrl = process.env.URL || "https://lupulsicorbul.com";

  return {
    // Payment configuration
    config: {
      emailTemplate: "",
      emailSubject: `Comandă ${paymentData.orderId} - Lupul și Corbul`,
      notifyUrl: `${baseUrl}/.netlify/functions/netopia-notify`,
      redirectUrl: `${baseUrl}/.netlify/functions/netopia-return`,
      language: "ro",
    },

    // Payment details
    payment: {
      options: {
        installments: 1,
        bonus: 0,
      },
      instrument: {
        type: "card", // Card payment
        account: "",
        expMonth: "",
        expYear: "",
        secretCode: "",
        token: "",
      },
      data: {
        // Additional payment data can go here
      },
    },

    // Order details
    order: {
      ntpID: "", // Will be generated by NETOPIA
      posSignature: "", // Not needed for API v2.x
      dateTime: new Date().toISOString(),
      description: paymentData.description || `Comandă ${paymentData.orderId}`,
      orderID: paymentData.orderId,
      amount: parseFloat(paymentData.amount),
      currency: "RON",

      // Billing information
      billing: {
        email: paymentData.customerInfo?.email || "test@lupulsicorbul.com",
        phone: paymentData.customerInfo?.phone || "+40700000000",
        firstName: paymentData.customerInfo?.firstName || "Test",
        lastName: paymentData.customerInfo?.lastName || "Customer",
        city: paymentData.customerInfo?.city || "Bucuresti",
        country: 642, // Romania country code
        countryName: "Romania",
        state: paymentData.customerInfo?.county || "Bucuresti",
        postalCode: paymentData.customerInfo?.postalCode || "010000",
        details: paymentData.customerInfo?.address || "Adresa test",
      },

      // Shipping information (same as billing for digital products)
      shipping: {
        email: paymentData.customerInfo?.email || "test@lupulsicorbul.com",
        phone: paymentData.customerInfo?.phone || "+40700000000",
        firstName: paymentData.customerInfo?.firstName || "Test",
        lastName: paymentData.customerInfo?.lastName || "Customer",
        city: paymentData.customerInfo?.city || "Bucuresti",
        country: 642,
        state: paymentData.customerInfo?.county || "Bucuresti",
        postalCode: paymentData.customerInfo?.postalCode || "010000",
        details: paymentData.customerInfo?.address || "Adresa test",
      },

      // Products
      products: [
        {
          name: paymentData.description || "Produs digital Lupul și Corbul",
          code: paymentData.orderId,
          category: "digital",
          price: parseFloat(paymentData.amount),
          vat: 19, // 19% TVA România
          quantity: 1,
        },
      ],

      // Installments
      installments: {
        selected: 1,
        available: [1],
      },

      data: {
        // Extra order data
        source: "lupulsicorbul.com",
        platform: "web",
      },
    },
  };
}

/**
 * Trimite request către NETOPIA API v2.x folosind API KEY
 */
async function initiateNetopiaV2Payment(payload, config) {
  console.log("🚀 Initiating NETOPIA API v2.x payment:", {
    baseUrl: config.baseUrl,
    orderId: payload.order.orderID,
    amount: payload.order.amount,
    hasApiKey: !!config.apiKey,
  });

  if (!config.apiKey) {
    throw new Error(
      "NETOPIA API KEY not configured. Please check environment variables."
    );
  }

  try {
    // API v2.x endpoint pentru start transaction
    const endpoint = `${config.baseUrl}/payment/card/start`;

    // Headers conform documentației
    const headers = {
      "Content-Type": "application/json",
      Accept: "application/json",
      Authorization: config.apiKey, // API KEY în header Authorization
      "User-Agent": "LupulSiCorbul/1.0 (contact@lupulsicorbul.com)",
    };

    console.log("📡 Sending request to NETOPIA API v2.x:", {
      endpoint,
      method: "POST",
      headers: {
        ...headers,
        Authorization: config.apiKey.substring(0, 10) + "...", // Nu logăm API KEY complet
      },
      payloadKeys: Object.keys(payload),
    });

    const response = await fetch(endpoint, {
      method: "POST",
      headers,
      body: JSON.stringify(payload),
    });

    console.log("📨 NETOPIA API v2.x Response:", {
      status: response.status,
      statusText: response.statusText,
      contentType: response.headers.get("content-type"),
    });

    // Verifică tipul de conținut pentru a determina cum să proceseze răspunsul
    const contentType = response.headers.get("content-type") || "";
    const isJson = contentType.includes("application/json");
    const isHtml = contentType.includes("text/html");

    if (!response.ok) {
      const errorText = await response.text();
      console.error("❌ NETOPIA API v2.x Error:", {
        status: response.status,
        statusText: response.statusText,
        body:
          errorText.substring(0, 500) + (errorText.length > 500 ? "..." : ""),
        contentType,
      });

      // Parse error response if it's JSON
      let errorDetails = errorText;
      try {
        if (isJson) {
          const errorJson = JSON.parse(errorText);
          errorDetails = errorJson.message || errorJson.error || errorText;
        }
      } catch (e) {
        // Keep original error text if not JSON
      }

      throw new Error(`NETOPIA API Error ${response.status}: ${errorDetails}`);
    }

    // Dacă primim HTML în loc de JSON, înseamnă că API v2.x nu este încă disponibil
    if (isHtml) {
      const htmlContent = await response.text();
      console.log(
        "🚨 NETOPIA API v2.x Request failed: Received HTML instead of JSON"
      );
      console.log(
        "📄 HTML Response preview:",
        htmlContent.substring(0, 200) + "..."
      );

      throw new Error(
        "NETOPIA API v2.x not available yet. Endpoint returns HTML interface instead of JSON API. " +
          "Please use API v1.x until v2.x is officially released."
      );
    }

    // Parse JSON response doar dacă avem JSON
    if (!isJson) {
      throw new Error(
        `Unexpected content type: ${contentType}. Expected application/json.`
      );
    }

    const responseData = await response.json();

    console.log("✅ NETOPIA API v2.x Response received:", {
      hasPayment: !!responseData.payment,
      hasPaymentUrl: !!responseData.payment?.paymentURL,
      paymentStatus: responseData.payment?.status,
      ntpID: responseData.payment?.ntpID,
      hasCustomerAction: !!responseData.customerAction,
    });

    // Verifică formatul răspunsului
    if (!responseData.payment) {
      throw new Error("Invalid response format from NETOPIA API v2.x");
    }

    const payment = responseData.payment;

    // Returnează rezultatul structurat
    return {
      success: true,
      paymentUrl: payment.paymentURL,
      orderId: payload.order.orderID,
      ntpID: payment.ntpID,
      status: payment.status,
      environment: config.baseUrl.includes("sandbox") ? "sandbox" : "live",
      apiVersion: "v2.x",
    };
  } catch (error) {
    console.error("🚨 NETOPIA API v2.x Request failed:", error.message);
    throw error;
  }
}

/**
 * Handler principal pentru Netlify Function
 */
export const handler = async (event, context) => {
  const headers = {
    "Access-Control-Allow-Origin": "*",
    "Access-Control-Allow-Headers": "Content-Type, Authorization",
    "Access-Control-Allow-Methods": "POST, OPTIONS",
    "Content-Type": "application/json",
  };

  // Handle CORS preflight
  if (event.httpMethod === "OPTIONS") {
    return { statusCode: 200, headers, body: "" };
  }

  if (event.httpMethod !== "POST") {
    return {
      statusCode: 405,
      headers,
      body: JSON.stringify({ error: "Method not allowed" }),
    };
  }

  // Declare paymentData outside try block so it's available in catch
  let paymentData;

  try {
    console.log("🌟 NETOPIA API v2.x - New payment initiation");

    // Parse request body
    try {
      let rawBody = event.body || "";
      if (event.isBase64Encoded) {
        rawBody = Buffer.from(rawBody, "base64").toString("utf-8");
      }
      paymentData = JSON.parse(rawBody || "{}");
    } catch (jsonError) {
      console.error("❌ JSON Parse Error:", jsonError.message);
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({
          error: "Invalid JSON in request body",
          details: jsonError.message,
        }),
      };
    }

    console.log("📋 Payment data received:", {
      orderId: paymentData.orderId,
      amount: paymentData.amount,
      currency: paymentData.currency,
      live: paymentData.live,
      hasCustomerInfo: !!paymentData.customerInfo,
      customerEmail: paymentData.customerInfo?.email,
    });

    // Validează datele obligatorii
    if (!paymentData.orderId || !paymentData.amount) {
      return {
        statusCode: 400,
        headers,
        body: JSON.stringify({
          error: "Missing required fields: orderId or amount",
        }),
      };
    }

    // Determină configurația (sandbox vs live)
    const baseUrl =
      process.env.URL ||
      context?.headers?.origin ||
      "https://lupulsicorbul.com";
    const isProduction =
      baseUrl.includes("lupulsicorbul.com") && !baseUrl.includes("localhost");
    const hasLiveCredentials = !!process.env.NETOPIA_LIVE_API_KEY;

    // Folosește live doar dacă suntem în producție și avem credențiale SAU dacă este forțat prin paymentData.live
    const useLive =
      (isProduction && hasLiveCredentials && paymentData.live !== false) ||
      (paymentData.live === true && hasLiveCredentials);
    const config = useLive ? NETOPIA_V2_CONFIG.live : NETOPIA_V2_CONFIG.sandbox;

    console.log("🔧 Environment configuration:", {
      baseUrl,
      isProduction,
      hasLiveCredentials,
      useLive,
      apiBaseUrl: config.baseUrl,
      hasApiKey: !!config.apiKey,
      apiKeyPreview: config.apiKey?.substring(0, 10) + "...",
    });

    // Verifică dacă avem API KEY
    if (!config.apiKey) {
      const missingKey = useLive
        ? "NETOPIA_LIVE_API_KEY"
        : "NETOPIA_SANDBOX_API_KEY";
      return {
        statusCode: 500,
        headers,
        body: JSON.stringify({
          error: "NETOPIA API KEY not configured",
          details: `Please set ${missingKey} environment variable`,
          environment: useLive ? "live" : "sandbox",
        }),
      };
    }

    // Creează payload-ul pentru NETOPIA API v2.x
    const payload = createNetopiaV2Payload(paymentData, config);

    // Inițiază plata folosind API v2.x
    const result = await initiateNetopiaV2Payment(payload, config);

    console.log("✅ Payment initiation successful:", {
      orderId: result.orderId,
      ntpID: result.ntpID,
      status: result.status,
      environment: result.environment,
      apiVersion: result.apiVersion,
    });

    // Returnează rezultatul
    return {
      statusCode: 200,
      headers,
      body: JSON.stringify({
        success: true,
        paymentUrl: result.paymentUrl,
        orderId: result.orderId,
        ntpID: result.ntpID,
        status: result.status,
        environment: result.environment,
        apiVersion: result.apiVersion,
        message: `Payment initiated successfully using NETOPIA API ${result.apiVersion}`,
      }),
    };
  } catch (error) {
    console.error("❌ Error in NETOPIA API v2.x handler:", error);

    return {
      statusCode: 500,
      headers,
      body: JSON.stringify({
        error: "Payment initiation failed",
        message: error.message,
        orderId: paymentData?.orderId || "unknown",
        timestamp: new Date().toISOString(),
      }),
    };
  }
};
