[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_ENV = "production" }

[build.environment]
  NODE_ENV = "production"
  VITE_NETOPIA_SANDBOX = "false"
  # IMPORTANT: Set these in Netlify Dashboard → Environment Variables:
  # VITE_FIREBASE_API_KEY = "your-firebase-api-key"
  # VITE_FIREBASE_AUTH_DOMAIN = "lupulcorbul.firebaseapp.com"
  # VITE_FIREBASE_PROJECT_ID = "lupulcorbul"
  # VITE_FIREBASE_STORAGE_BUCKET = "lupulcorbul.firebasestorage.app"
  # VITE_FIREBASE_MESSAGING_SENDER_ID = "312943074536"
  # VITE_FIREBASE_APP_ID = "1:312943074536:web:13fc0660014bc58c5c7d5d"
  # VITE_FIREBASE_MEASUREMENT_ID = "G-38YSZKVXDC"
  # VITE_OPENAI_API_KEY = "your-openai-api-key"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[dev]
  command = "vite"
  port = 8888         # Netlify Dev va servi pe acest port
  targetPort = 5173   # Vite va rula pe acest port (default)
  functions = "netlify/functions"
  publish = "dist"
  autoLaunch = false

# Redirectări pentru SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache Control pentru fișierele statice
[[headers]]
  for = "/*.(js|css|svg|jpg|jpeg|png|gif|webp|ico|woff|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Activăm comprimarea Brotli și GZIP
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true