[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"

[dev]
  command = "vite"
  port = 8888         # Netlify Dev va servi pe acest port
  targetPort = 5173   # Vite va rula pe acest port (default)
  functions = "netlify/functions"
  publish = "dist"
  autoLaunch = false

# Redirectări pentru SPA (Single Page Application)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache Control pentru fișierele statice
[[headers]]
  for = "/*.(js|css|svg|jpg|jpeg|png|gif|webp|ico|woff|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Activăm comprimarea Brotli și GZIP
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true