[build]
  # Build command compatible with both Windows (local) and Linux (Netlify)
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  GENERATE_SOURCEMAP = "false"
  NODE_OPTIONS = "--max-old-space-size=4096"
  # Set NODE_ENV for production builds
  NODE_ENV = "production"
  # Forțează versiunea Node.js mai nouă pentru a evita deprecated Focal image
  NODE_VERSION = "18"
  # NODE_ENV va fi setat explicit doar pentru production builds, nu pentru dev
  # NODE_ENV = "production"  # Commented out to fix React dev mode
  # Exclude Netopia signature and Firebase API key from secret scanning
  SECRETS_SCAN_OMIT_KEYS = "VITE_NETOPIA_SIGNATURE_LIVE,VITE_FIREBASE_API_KEY"
  # Disable secret scanning to prevent build failures due to placeholder references
  SECRETS_SCAN_ENABLED = "false"
  
  # Firebase Configuration pentru Netlify Build
  VITE_FIREBASE_API_KEY = "AIzaSyCZEWoZn-c7NSH1AGbetWEbtxwEz-iaMR4"
  VITE_FIREBASE_AUTH_DOMAIN = "lupulcorbul.firebaseapp.com"
  VITE_FIREBASE_PROJECT_ID = "lupulcorbul"
  VITE_FIREBASE_STORAGE_BUCKET = "lupulcorbul.firebasestorage.app"
  VITE_FIREBASE_MESSAGING_SENDER_ID = "312943074536"
  VITE_FIREBASE_APP_ID = "1:312943074536:web:13fc0660014bc58c5c7d5d"
  VITE_FIREBASE_MEASUREMENT_ID = "G-38YSZKVXDC"

[dev]
  # Servește direct din dist/ fără proxy către Vite
  port = 8888
  functions = "netlify/functions"
  
[dev.environment]
  # Override pentru dezvoltare locală - React trebuie să ruleze în development mode
  NODE_ENV = "development"
  VITE_ENVIRONMENT = "development"
  # Base URL for local development (Netlify Dev)
  URL = "http://localhost:8888"
  NETOPIA_SANDBOX_SIGNATURE = "2ZOW-PJ5X-HYYC-IENE-APZO"
  # Sandbox Netopia credentials (set your PEM blocks here for local testing or configure in Netlify UI)
  NETOPIA_SANDBOX_PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----\nMIICeAIBADANBgkqhkiG9w0BAQEFAASCAmIwggJeAgEAAoGBAPWF5TRG+VH3kcWa\ncheCdCB/EwUZYFELepVGldTsDIt/w7h9Bi/55+Eq0HjBp9zqMrz90jZh67akEQKb\nx1ilA87XkrBKXTvGzyszglz6UbfLhuLg1UfmjJst9cOtwPOAdL30wNewKHv2uJio\nwqqolt+OImKm0MO0/+MM/z8n4szPAgMBAAECgYEA8JL6O3cv5TkIBO+Iy7BvyUe6\ng0ySK9drjclUFwYUZLwUMzmOToQ4yVECZNCcgsKYZMbwq4jXRmcMo9mwQxOt3Zvc\nukwcwbnhDbUY2pgEr+SMasYzEErg+pJLhLkWCs8tJL+YppV30+i9JT9LelekBwY3\nbQmWdbaLv56P+5w7QIECQQD7SmicemdHGwmhEz13nbOynmP0h5nXY3yFYYkKmUSn\nR6VpunCD9G3thIBJfFVyg4EDHqOQIMekypTcd8XRAmHJAkEA+h/Q4Hia8EXJA6hf\nATkaasI6R79ZriOUpa82wo7W2jqSGQ1UtujY3n7TuNuE0GjISgYwbhcowabJKEVJ\n5gvF1wJAVjYM9cI4tHheMVi8edEs2Vbly/rJmM+U5N21emFi4FEAOumvuFWfcSFI\nMe3qEsNy+3MDgmr8k1i9AXZF85LxoQJBALRifaFlWVgu++lHZDzdkc+sg5t6xJJx\n1qIm2rc1jH2WAAdRNeczxjOwA8Etj3s+FjRMgmDjEuGWBzyju8fMdcECQQCj/DtM\n+b7wtPqMtet6cbf8Mc45vJnvmIpviG/BMYi8dlQFty1gzw/dyn4CLNM47umAVxTR\n9JSX2ToP3Qt102qK\n-----END PRIVATE KEY-----"
  NETOPIA_SANDBOX_PUBLIC_CERT = "-----BEGIN CERTIFICATE-----\nMIIC3zCCAkigAwIBAgIBATANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCUk8x\nEjAQBgNVBAgTCUJ1Y2hhcmVzdDESMBAGA1UEBxMJQnVjaGFyZXN0MRAwDgYDVQQK\nEwdORVRPUElBMSEwHwYDVQQLExhORVRPUElBIERldmVsb3BtZW50IHRlYW0xHDAa\nBgNVBAMTE25ldG9waWEtcGF5bWVudHMucm8wHhcNMjUwNzEzMTI0ODM0WhcNMzUw\nNzExMTI0ODM0WjCBiDELMAkGA1UEBhMCUk8xEjAQBgNVBAgTCUJ1Y2hhcmVzdDES\nMBAGA1UEBxMJQnVjaGFyZXN0MRAwDgYDVQQKEwdORVRPUElBMSEwHwYDVQQLExhO\nRVRPUElBIERldmVsb3BtZW50IHRlYW0xHDAaBgNVBAMTE25ldG9waWEtcGF5bWVu\ndHMucm8wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALwh0/NhEpZFuKvghZ9N\n75CXba05MWNCh422kcfFKbqP5YViCUBg3Mc5ZYd1e0Xi9Ui1QI2Z/jvvchrDZGQw\njarApr3S9bowHEkZH81ZolOoPHBZbYpA28BIyHYRcaTXjLtiBGvjpwuzljmXeBoV\nLinIaE0IUpMen9MLWG2fGMddAgMBAAGjVzBVMA4GA1UdDwEB/wQEAwIFoDATBgNV\nHSUEDDAKBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ9yXCh\nMGxzUzQflmkXT1oyIBoetTANBgkqhkiG9w0BAQsFAAOBgQAMnh95YlI+y3XcxrpG\ngNWC9AwVBt61MTid213yuXDGxkouizSGFr1MjP1tk/YkcWdNka9QB3AtCr4bMers\n/2f322soXcrhAOhj5JPVQkF6rlhJxg2JBO+8M5sOJTaxq5YvFHl/o2GGg0UuxWb5\nRbUx6W/CU+uFDgDY8CdZ3hZ7kg==\n-----END CERTIFICATE-----"
  # Provide the sandbox public key for client config
  NETOPIA_SANDBOX_PUBLIC_KEY = "-----BEGIN CERTIFICATE-----\nMIIC3zCCAkigAwIBAgIBATANBgkqhkiG9w0BAQsFADCBiDELMAkGA1UEBhMCUk8x\nEjAQBgNVBAgTCUJ1Y2hhcmVzdDESMBAGA1UEBxMJQnVjaGFyZXN0MRAwDgYDVQQK\nEwdORVRPUElBMSEwHwYDVQQLExhORVRPUElBIERldmVsb3BtZW50IHRlYW0xHDAa\nBgNVBAMTE25ldG9waWEtcGF5bWVudHMucm8wHhcNMjUwNzEzMTI0ODM0WhcNMzUw\nNzExMTI0ODM0WjCBiDELMAkGA1UEBhMCUk8xEjAQBgNVBAgTCUJ1Y2hhcmVzdDES\nMBAGA1UEBxMJQnVjaGFyZXN0MRAwDgYDVQQKEwdORVRPUElBMSEwHwYDVQQLExhO\nRVRPUElBIERldmVsb3BtZW50IHRlYW0xHDAaBgNVBAMTE25ldG9waWEtcGF5bWVu\ndHMucm8wgZ8wDQYJKoZIhvcNAQEBBQADgY0AMIGJAoGBALwh0/NhEpZFuKvghZ9N\n75CXba05MWNCh422kcfFKbqP5YViCUBg3Mc5ZYd1e0Xi9Ui1QI2Z/jvvchrDZGQw\njarApr3S9bowHEkZH81ZolOoPHBZbYpA28BIyHYRcaTXjLtiBGvjpwuzljmXeBoV\nLinIaE0IUpMen9MLWG2fGMddAgMBAAGjVzBVMA4GA1UdDwEB/wQEAwIFoDATBgNV\nHSUEDDAKBggrBgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MB0GA1UdDgQWBBQ9yXCh\nMGxzUzQflmkXT1oyIBoetTANBgkqhkiG9w0BAQsFAAOBgQAMnh95YlI+y3XcxrpG\ngNWC9AwVBt61MTid213yuXDGxkouizSGFr1MjP1tk/YkcWdNka9QB3AtCr4bMers\n/2f322soXcrhAOhj5JPVQkF6rlhJxg2JBO+8M5sOJTaxq5YvFHl/o2GGg0UuxWb5\nRbUx6W/CU+uFDgDY8CdZ3hZ7kg==\n-----END CERTIFICATE-----"

# Redirectări pentru SPA (Single Page Application)
[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

# CRITICAL: Protejăm rutele specifice de aplicație înainte de fișierele statice
[[redirects]]
  from = "/payment-simulation"
  to = "/index.html"
  status = 200
  headers = {Cache-Control = "no-cache, no-store, must-revalidate", Pragma = "no-cache", Expires = "0"}

[[redirects]]
  from = "/payment-simulation/*"
  to = "/index.html"
  status = 200
  headers = {Cache-Control = "no-cache, no-store, must-revalidate", Pragma = "no-cache", Expires = "0"}

# Protecția pentru fișierele statice din directorul assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Servim fișierele statice doar cu extensiile corecte
[[redirects]]
  from = "/assets/*.js"
  to = "/assets/:splat"
  status = 200
  headers = {Content-Type = "application/javascript"}

[[redirects]]
  from = "/assets/*.mjs"
  to = "/assets/:splat"
  status = 200
  headers = {Content-Type = "application/javascript"}

[[redirects]]
  from = "/assets/*.css"
  to = "/assets/:splat"
  status = 200
  headers = {Content-Type = "text/css"}

[[redirects]]
  from = "/assets/*.svg"
  to = "/assets/:splat"
  status = 200
  headers = {Content-Type = "image/svg+xml"}

[[redirects]]
  from = "/assets/*.png"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/assets/*.jpg"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/assets/*.jpeg"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/assets/*.gif"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/assets/*.ico"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/assets/*.woff"
  to = "/assets/:splat"
  status = 200

[[redirects]]
  from = "/assets/*.woff2"
  to = "/assets/:splat"
  status = 200

# Doar DUPĂ toate fișierele statice și rutele protejate, redirecționează totul către SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache Control pentru fișierele statice
[[headers]]
  for = "/assets/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "application/javascript; charset=utf-8"

[[headers]]
  for = "/assets/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    Content-Type = "text/css; charset=utf-8"

[[headers]]
  for = "/*.(css|svg|jpg|jpeg|png|gif|webp|ico|woff|woff2)"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Special headers pentru pagina de simulare - no cache
[[headers]]
  for = "/payment-simulation"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"
    Pragma = "no-cache"
    Expires = "0"
    X-Robots-Tag = "noindex, nofollow"

# Activăm comprimarea Brotli și GZIP
[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true